# Generated by Django 3.2.7 on 2021-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
